//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___RoutingLogic {
  func routeToSomewhere()
}

protocol ___VARIABLE_sceneName___DataPassing {
  var dataStore: ___VARIABLE_sceneName___DataStore? { get }
}

class ___VARIABLE_sceneName___Router: NSObject, ___VARIABLE_sceneName___RoutingLogic, ___VARIABLE_sceneName___DataPassing {
  var viewController: ___VARIABLE_sceneName___ViewController?
  var dataStore: ___VARIABLE_sceneName___DataStore?
  
  // MARK: Routing

  func routeToSomewhere() {
    routeToSomewhere(segue: nil)
  }
  
  func routeToSomewhere(segue: UIStoryboardSegue?) {
    if let segue = segue {
      let destinationVC = segue.destination as! ___VARIABLE_sceneName___ViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataTo(&destinationDS, from: dataStore!)
    } else {
      let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SomewhereViewController") as! ___VARIABLE_sceneName___ViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataTo(&destinationDS, from: dataStore!)
      viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
  }
  
  // MARK: Data Passing
  
  func passDataTo(_ destinationDS: inout ___VARIABLE_sceneName___DataStore, from sourceDS: ___VARIABLE_sceneName___DataStore) {
    destinationDS.attribute = sourceDS.attribute
  }
}
