//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

class ___VARIABLE_sceneName___WorkerTests: XCTestCase {

  // MARK: Subject Under Test (SUT)
  
  var sut: ___VARIABLE_sceneName___Worker!
  
  // MARK: Test Lifecycle
  
  override func setUp() {
    super.setUp()
    setup___VARIABLE_sceneName___Worker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test Setup
  
  func setup___VARIABLE_sceneName___Worker() {
    sut = ___VARIABLE_sceneName___Worker()
  }
  
  // MARK: Test Doubles
  
  // MARK: Tests
  
  func test___VARIABLE_sceneName___() {
    
    // Given
    
    // When
    
    // Then
  }
}
